version: '3.5'

services:
    react-service:
        container_name: react-container
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - "3000:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true